microservice:   ## general service details 
  name: travelreg-submission-api
  namespace: travelreg-submission
  replicas: 2

workload:   ## container specific configurations
  image: rslim087/kubernetes-course-grade-submission-api:stateless-v2
  port: 3000
  resources:
    memory: "128Mi"
    cpu: "128m"
  livenessDelay: 15

secrets:  ## sensitive data
  MONGODB_URI: 'mongodb://user:password123@mongodb.mongodb.svc.cluster.local:27017/travelreg'
  